services:
 
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432
#     volumes:
# - pgdata:/var/lib/postgresql/data
#
#docker compose -f docker-compose.yml  up
#docker compose -f docker-compose.yml down
#